### PR TITLE
Don't auto-expand item/option-sets in existing content #1497

### PR DESCRIPTION
**Pull request by ashklianko**

### CODE REVIEW

**Comment by jsi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/resources/assets/admin/common/js/form/set/FormSetView.ts  8
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/enonic/lib-admin-ui/pullRequest?prid=6324552&bid=20554682)

**Review by alansemenov — CHANGES_REQUESTED** [review]
With these changes an item-set is by default collapsed in a **new** content with the schema below, which is against the requirements. In a new content, item- and option-sets should be expanded by default, as before.

image

```XML
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<content-type>
  <display-name>Item set</display-name>
  <super-type>base:structured</super-type>
  <form>
    <item-set name="my-item-set">
      <label>My item set</label>
      <occurrences minimum="1" maximum="1"/>
      <items>
        <input name="label" type="TextLine">
          <label>Label</label>
          <occurrences minimum="1" maximum="1"/>
        </input>
      </items>
    </item-set>
  </form>
</content-type>
```

**Comment by ashklianko** [comment]
Updated

**Comment by jsi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/resources/assets/admin/common/js/form/set/FormSetView.ts  8
- src/main/resources/assets/admin/common/js/form/FormContext.ts  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/enonic/lib-admin-ui/pullRequest?prid=6324552&bid=20554682)

**Review by alansemenov — APPROVED** [review]

**Pull request merged**
