### PR TITLE
Implement new dropdown control for sorting dialog #479

### PR DESCRIPTION
**Pull request by edloidas**
Added customization of the TabMenu.

### CODE REVIEW

**Comment by alansemenov** [comment]
Great stuff

**Comment by sigdestad** [comment]
Only thing is that the arrows should point up and down (now both point down)

**Comment by sigdestad** [comment]
Or, down and up it should be I guess :-)

**Comment by edloidas** [comment]
Well, it's either we use these icoMoon icons or use the arrows only. You see, they were designed with changes the order of the numbers (`1..9` => `9..1`) or letters (`A..Z` => `Z..A`). We don't have any other variations. BTW we use those icons for a long time now in the grid to show the content order.

**Comment by alansemenov** [comment]
Yes, the icons were designed this way for a reason. Arrows represent the direction the items are listed in.

**Pull request merged**
