### PR TITLE
Translate the Admin UI to Polish

### PR DESCRIPTION
**Pull request by MichalKlimekPlativo**

### CODE REVIEW

**Comment by alansemenov** [comment]
Hi @MichalKlimekPlativo! 

Thank you for the translations - looking forward to having XP available in Polish! However, in this repository we only have a half of the phrases, the "common" ones. 

The rest is here: https://github.com/enonic/xp-apps/tree/master/modules. Each of these modules has ``i18n`` folder with the localisation packages. For example, this is for Content Studio: https://github.com/enonic/xp-apps/tree/master/modules/app-contentstudio/src/main/resources/i18n

Do you think you can translate these too? That would be fantastic.

Thanks!

**Comment by MichalKlimekPlativo** [comment]
Hi Alan!

I'm working on it. Will be translated in few days :)

Kind regards,

Michał Klimek
CEO

+48 609 608 468 | michal.klimek@plativo.com 
<mailto:michal.klimek@plativo.com> | skype: michal.klimek.plativo

Plativo Sp. z o. o. [Ltd.] | +48 222411869 | ul. Nowy Świat 49 lok. 213, 
00-042 Warsaw Poland | plativo.com <http://plativo.com/en.html>

------------------------------------------------------------------------
W dniu 2018-02-06 o 10:49, Alan Semenov pisze:

**Comment by MichalKlimekPlativo** [comment]
Hi Alan,
I added the pull request with the rest :)

Kind regards,

Michał Klimek
CEO

+48 609 608 468 | michal.klimek@plativo.com 
<mailto:michal.klimek@plativo.com> | skype: michal.klimek.plativo

Plativo Sp. z o. o. [Ltd.] | +48 222411869 | ul. Nowy Świat 49 lok. 213, 
00-042 Warsaw Poland | plativo.com <http://plativo.com/en.html>

------------------------------------------------------------------------
W dniu 2018-02-06 o 10:49, Alan Semenov pisze:

**Comment by alansemenov** [comment]
@MichalKlimekPlativo Hi Michal! Now we have XP available in Polish - fantastic job! Now and then we add new texts to the admin and then we will need your help again to translate those as well, but it's usually a couple of phrases every 2 months or something like that. Appreciate your help 👍

**Pull request merged**
