### PR TITLE
Browse Panel - Ditch tablet mode #111

### PR DESCRIPTION
**Pull request by pmi**

### CODE REVIEW

**Comment by alansemenov** [comment]
@pmi Works fine, but now when the page is in tablet width and detail panel is expanded, there's not much space left for the preview (see below). We should change it so that detail panel goes in floating mode on widths > mobile and < tablet (basically same as when we used to switch preview to be under the grid).

image

**Comment by sigdestad** [comment]
Hmm. Looking at Alans screenshot. I think what is wrong is that there should be a minimum width for the "grid" as long as we are operating in a split screen mode. Can we try "freezing" at a minimum of 300px before we make changes to the preview panel. We carefully crafted how the detail panel should work in these cases, and I would like to move carefully when changing these things.

**Comment by sigdestad** [comment]
So to followup - For the screen resolution above we should probably already use mobile mode?

**Comment by alansemenov** [comment]
> For the screen resolution above we should probably already use mobile mode?

I'm not so sure. 768px width is enough for both the grid and the preview side by side, it's only when the details panel expands when the preview panel gets squeezed between that and the grid.

Grid width is already set to 300px in tablet mode (with remaining 468 for the preview panel).

**Comment by sigdestad** [comment]
Hmm.. I thought we said to use mobile mode for <960px?

**Comment by alansemenov** [comment]
This is what we have now:

Mobile (slide-in preview): width < 540px
Tablet (preview at the bottom): 540px < width < 720px
Desktop (preview to the right): width > 720px

After removal of the tablet mode it's mobile mode under 540 and desktop over 540.

A threshold of 960px is used only in the Wizard to determine whether the Page Editor should be visible by default or not.

Should we say that anything under 960px is "mobile" mode with the right panel hidden by default in both the Grid and the Wizard?

What I don't like in mobile preview is that you cannot see both the grid and the preview at the same time. While it's necessary on low resolutions (under 540) it doesn't make much sense on, say, 959px - there's plenty of room to show both the grid and the preview side by side. Maybe we should use 720px as mobile/desktop threshold?

**Comment by sigdestad** [comment]
Lets try 720 then!

**Pull request merged**
